### ISSUE TITLE
Add mentions in comments 

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/GDPyS#20]
If someone mentions a user in a comment (eg @BruhMan) they will receive a message from GDPyS Bot that says the level name, level Id, comment content and the name of the person who mentioned the user. Make the amount of messages limited so people don't abuse this to spam people.

**Comment by RealistikDash** [comment]
Still valid

**Comment by spookybear0** [comment]
This should be easy.

**Comment by RealistikDash** [comment]
Yeah, just need to look for an @ symbol. Will require for the bot to be functional with at least basic functionality (such as sending messages to users which itself will have to wait for the message system to work).
