### ISSUE TITLE
Finish plugin system and fix listeners.

### ISSUE THREAD

**Issue by spookybear0** [RealistikDash/GDPyS#23]
Listeners do not work at all.

**Comment by Stazzical** [comment]
listeners would be a part of the plugin sdk, and commands is much better to be a plugin

**Comment by spookybear0** [comment]
Commands can be used in plugins, for example if I wanted to make a plugin that would ban somebody I would use the Commands class and create a new command.

**Comment by Stazzical** [comment]
Those stuff you mean will be in the plugin SDK, but the "commands" plugin will be for in-game comments on a level or a message to the server bot which will have slightly different syntax to the commands used in a level's comment section.

**Comment by spookybear0** [comment]
I just want to let you know that there are NO built in plugins, the commands class will remain native.

**Comment by Stazzical** [comment]
All stuff you need will be in the plugin SDK, so you should be alright with it, and commands for in-game comments or messages to the server bot better be a plugin for more flexibility, for example if they want to change the syntax or make a custom command with the plugin SDK. I just don't see a reason why we shouldn't make it a plugin and you are telling me it's not a good idea while it is.

**Comment by spookybear0** [comment]
Why should it be a plugin when it could be in the SDK, commands are important. Just how spigot lets you make commands.

**Comment by Stazzical** [comment]
As I said, making it a plugin makes it flexible, also "commands" plugin will be in-game, and we will implement things like rate(), epic(), etc. in the SDK, and commands plugin will make these available through the game, nothing so special, I don't see why you should implement in-game commands in the SDK and how many times I have to explain this to you, ugh.

**Comment by spookybear0** [comment]
@RealistikDash please tell @Intelligent-Cat why making something that should be a native feature a plugin is a bad idea, it takes such a small amount of code to add the commands system to the main sdk.

**Comment by spookybear0** [comment]
Outdated.

**Comment by Dxrkify** [comment]
I'LL FUCKING FUCK YOU

**Comment by Dxrkify** [comment]
FUCK FACE
