### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/GDPyS#24]
The current plugin system uses asyncio.run which was added in python 3.7. This will make GDPyS not work correctly in Python implementations such as PyPy.

**Comment by spookybear0** [comment]
@RealistikDash I will fix this tomorrow. Please assign me.

**Comment by RealistikDash** [comment]
Assigned

**Comment by spookybear0** [comment]
@RealistikDash Link #26
