### ISSUE TITLE
Extend the permission system

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/GDPyS#29]
Here is the plan:

- Add more permission enums
- Add more permission checks when necessary
- Create an easy way to create privilege groups

**Comment by spookybear0** [comment]
Maybe we could make it like how we wanted banned users not seeing leaderboards being configurable? For example, block the request and return -1 if permission is false.

**Comment by RealistikDash** [comment]
Possible

**Comment by Dxrkify** [comment]
Afgqcfrbrjtuewfwbjtjtjdbgrytub

**Comment by RealistikDash** [comment]
Thank you dark, very cool!

**Comment by Dxrkify** [comment]
![image](https://user-images.githubusercontent.com/65834882/90700309-6e725f00-e27d-11ea-8b40-a86f03fd2fa7.jpeg)

**Comment by spookybear0** [comment]
![image](https://user-images.githubusercontent.com/50897638/90700472-cc318780-e23a-11ea-81d0-5e127ba3d06d.png)

**Comment by RealistikDash** [comment]
Closed due to v1 being deprecated.
