### ISSUE TITLE
(rewrite) re-create plugin system

### ISSUE THREAD

**Issue by spookybear0** [RealistikDash/GDPyS#38]
maybe like discord.py cogs.

**Comment by Dxrkify** [comment]
NO!!!

**Comment by ghost** [comment]
yes

**Comment by RealistikDash** [comment]
Yeah I like discord.py s cog system and it will fit with rewrites async object oriented design

**Comment by Dxrkify** [comment]
NO!!!

**Comment by spookybear0** [comment]
closing as it has been finished
