### ISSUE TITLE
if possible, add a texture pack manager

### ISSUE THREAD

**Issue by efwxx** [RealistikDash/GDPyS#41]
you read the title. try to add a texture pack manager. it would make a separate file (for example, packs) where you can store texture packs in. using an external program, you can switch between normal gd texture pack (resources folder) and other texture packs installed. lmk if needs more clarification.

**Comment by Dxrkify** [comment]
isn't this client sided

**Comment by PhyteGD** [comment]
Yes dark, this is client sided

**Comment by spookybear0** [comment]
close this @RealistikDash

**Comment by RealistikDash** [comment]
Closed as that idea is client sided. GDPyS only handles the server-side and will likely always remain that way. That may be a decent idea for a separate project though.

**Comment by spookybear0** [comment]
lets test this @RealistikDash#0077

**Comment by RealistikDash** [comment]
👀

**Comment by efwxx** [comment]
:trollface:

**Comment by fancythedeveloper** [comment]
@ElectroFlameOfficial Check out Poweredbypie's TextureLDR

**Comment by efwxx** [comment]
I know, that was long before TextureLDR got released.

**Comment by fancythedeveloper** [comment]
Oh, just realized, lol.
