### ISSUE TITLE
On rate CP calculation.

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/GDPyS#43]
When a level is rated, the cp values for the cached obj should be locally updated or even updated in the db,

**Comment by Dxrkify** [comment]
PP CALCULATION

**Comment by RealistikDash** [comment]
CP lmfao

**Comment by Dxrkify** [comment]
We found him. We found the weeb.

**Comment by RealistikDash** [comment]
zdfghghghghghghghghghghghghghghghghghghghgzfDddddddhfgzzzzzzzzzz

**Comment by PhyteGD** [comment]
Get that osu shit out of the GD Chad Zone

**Comment by RealistikDash** [comment]
Added with commit cd3c9a0
