### ISSUE TITLE
New Caching System

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/GDPyS#67]
GDPyS is severely in need of a new caching system. Currently, there are ~4 individual caching systems in the classes that use them. This means that there are essentially identical implementations of caching repeated multiple times throughout the codebase. This means that if I were to want to make a change to the caching system, I would be required to implement that change 4 times. The caching system is just mixed with the rest of the code without any care or separation. The current way makes it hard to add more caches to speed up more actions.

However, there are more reasons than just code maintainability. Firstly, there is no cache limit. This means that stuff can keep on being added onto the cache, potentially causing the host to run out of memory. While this has not happened during testing, it can become a major issue of servers with large player bases and large databases.

Secondly, the current cache has no expiry date. This means that outdated cached data can stay on the server potentially forever (or until a server restart) if it were to be updated without consideration for cached data. This can be a major problem during surges of activity or really anytime.

## Requirements for a new system.
- It is its own system, not integrated into any particular function.
- It preferably uses a class based design, meaning a new cache can just be created by doing something along the lines of `Cache()`
- There is a customisable limit to how many objects can be cached.
- It allows to retrieve objects by ID (such as getting user object from cache by using the account id).
- Cache can expire after a customisable amount of time. Checking for expired cache can be done during caching of an object or fetching of an object.

**Comment by RealistikDash** [comment]
This is almost complete. All we need is to add this new system to userhelper

**Comment by spookybear0** [comment]
Is this completed?

**Comment by RealistikDash** [comment]
Needs to be fully implemented such as in the userhelper etc

**Comment by RealistikDash** [comment]
Irrelevant for GDPyS v3, which has an improved implementation of the same caching system within its core.
