### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Partur-dev** [RealistikDash/GDPyS#68]
![image](https://user-images.githubusercontent.com/57731289/96785941-35c74100-13f8-11eb-833a-082ca52d7450.png)
![image](https://user-images.githubusercontent.com/57731289/96785968-3d86e580-13f8-11eb-80fc-aba095f694ce.png)

**Comment by RealistikDash** [comment]
You may access the server through 127.0.0.1 (0.0.0.0 just means the server is open to outside connections too). Also, the `Event loop is closed` error is mostly caused by a KeyboardInterrupt.

**Comment by spookybear0** [comment]
Did you do ctrl-c?

**Comment by RealistikDash** [comment]
Closed due to lack of info
