### ISSUE TITLE
Inconsistency in User ID field naming.

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/GDPyS#86]
Within the code, the `user_id` is occasionally referred to as `account_id`. This can prompt confusion, where users are likely to think that they are different from each other while refering to exactly the same thing. An example of this is between account comments and regular comments, where account comments refer to the id of the user as an `account_id` while comments refer to it as `user_id`. This must be changed project-wide, where `user_id` should be the correct way to refer to the id of an user.

**Comment by apinanyogaratnam** [comment]
I can handle this issue.

**Comment by RealistikDash** [comment]
Alright perfect! I have just commited the newest MySQL database schema

**Comment by apinanyogaratnam** [comment]
completed and successfully merged. This may be closed.

**Comment by RealistikDash** [comment]
Solved by #87
