### ISSUE TITLE
Fix song crawling triggering the firewall

### ISSUE THREAD

**Issue by RealistikDash** [RealistikDash/GDPyS#88]
Currently, attempting to crawl a song from the official GD servers using Rob's client endpoint triggers the newly implemented Cloudflare firewall, resulting in the error 1020.

There are 2 ways to approach this:
- Attempt to bypass Rob's firewall by mirroring a request made by GD as closely as possible (may include mirroring headers + post data)
- Bypass GD servers completely and crawl from Newgrounds (will also allow to bypass unscouted songs).

**Comment by fancythedeveloper** [comment]
The 2nd option might be better, since it will also allow for unscouted
songs.

**Comment by RealistikDash** [comment]
Issue solved with latest commit (667e360), using Newgrounds directly (also allows us to use unscouted songs)!
